### ISSUE TITLE
Exception on resume Android app

### ISSUE THREAD

**Issue by deus82ex** [NordicID/rfiddemo_xamarin#1]
Hi,

in Android Project MainActivity OnCreate you have to call:
//Prepare NurApi and NurDeviceDiscovery instances for this platform.                       App.Nur.Init(Application.Context);
App.NurDeviceSearch.Init(Application.Context);

When the App pauses and then on resume this call throws an exception, because init has already been executed. How can I check if init is already done, or how can I destroy init in OnPause?

Regards Mario

**Comment by AriPoy** [comment]
Sorry for late reply..
There is now changes for device discovery functionality. Please try with new version (3.0.0)
Please note that NurApi.Net ver 3.0.0 is not code compatible with ver 2.0.0 so you need to do some migration job in your code.
