### ISSUE TITLE
HowTo read TID tag

### ISSUE THREAD

**Issue by graselli** [NordicID/rfiddemo_xamarin#2]
Hi, I don't find a way to read TID bank of the tag. 
I'm following the example in the documentation but I receive only timeout exception

int rdByteCount;
byte []userMemory;

rdByteCount = 4 // try with other values with the same result

try
{
    []userMemory = aTag.ReadTag(0, false, NurApi.BANK_TID, 0, rdByteCount);
}
catch (NurApiException e)
{
    ...
}

**Comment by AriPoy** [comment]
Hi, you should able to read TID using ReadTag after inventory performed. Then select tag from reading result for ReadTag operation. Sample:
```
Console.WriteLine("making simple inventory using existing settings..");
nur.Inventory();                
TagStorage tags=nur.FetchTags(); //Fetch tags from module
if (tags.Count > 0)
{
         //Iterate results
        foreach (Tag tag in tags)
        {
                //Tag is now near and available. Read TID.                        
                byte[] tid = tag.ReadTag(0, false, NurApi.BANK_TID, 0, 4);
                Console.WriteLine("EPC=" + tag.GetEpcString() + " TID=" + NurApi.BinToHexString(tid));
                //Other option to read other bank with EPC with same inventory round. Use InventoryRead.
        }
}
else 
       Console.WriteLine("No tags seen..");
```
Consider to use InventoryRead as it can read EPC + other bank using same inventory round.
Sample:
```
IrInformation ir = new IrInformation();
ir.active = true; //InventoryRead is now active     
ir.type = NurApi.NUR_IR_EPCDATA;
ir.bank = NurApi.BANK_TID;
ir.wAddress = 0;
ir.wLength = 2;                                    
nur.SetInventoryRead(ir); //Set
nur.Inventory(); //Perform inventory
tags = nur.FetchTags(); //Fetch tags from module
if (tags.Count > 0)
{
         //Iterate results
         foreach (Tag tag in tags)
         {
             //EPC + TID (tag.irData contains TID data)
             Console.WriteLine("EPC=" + tag.GetEpcString() + " TID=" + NurApi.BinToHexString(tag.irData));                        
          }
}
else                
        Console.WriteLine("No tags seen..");

ir.active = false; //Remember to disable InventoryRead when not used anymore.
nur.SetInventoryRead(ir);
```

**Comment by graselli** [comment]
it does'nt work

this is the result 

[0:] NurCmdInventory[0x31] Error: ExecFail; NUR API error 96: HW error
01-21 09:12:08.874 I/Choreographer(10501): Skipped 64 frames!  The application may be doing too much work on its main thread.
**NurApiDotNet.NurApiException:** 'ExecFail; NUR API error 96: HW error'

**Comment by graselli** [comment]
UPDATE! 
After restart device the code seems to work but it doesn't do what it should do.... 
the TID returned is smaller than what I expected and it'not unique across the tags
maybe I lack in some information
My goal is:

count the phisical number of tags series with the same EPC value.

I.E: 

if I scan a table with 
rfid1: EPC:12345678
rfid2: EPC:12345678
rfid3: EPC:99999999

I would need as response:
EPC:12345678 --> 2 pieces
EPC:99999999 --> 1 piece
