### ISSUE TITLE
Xamarin iOS support?

### ISSUE THREAD

**Issue by timahrentlov** [NordicID/rfiddemo_xamarin#6]
Hi,

Is Xamarin iOS supported. If I look into the iOS project the NordicId.NurApi.iOS (and NordicID.NurApi.Net) is not resolved. They seem to be missing as project references.

**Comment by Buryyy** [comment]
Hi @timahrentlov!

Yes, Xamarin.iOS is supported. The NordicId.NurApi.iOS and NordicID.NurApi.Net used to be locally referenced dlls. 

Closing this issue, as this is resolved with #7.

**Comment by timahrentlov** [comment]
Yes. I can confirm that it is now available as a nuget. Thanks!

<img width="353" alt="Screenshot 2023-05-04 at 14 13 41" src="https://user-images.githubusercontent.com/1124919/236207148-f95d2ede-742e-49e5-a24e-f156e51169db.png">
